let cartas = [
    {
        nombre: "Ticci Toby",
        imagen: "https://i.pinimg.com/736x/78/f7/39/78f739458a78aef2f3c82f404c04c741.jpg",
        descripcion: "Ticci Toby es un joven con tics nerviosos y un pasado traumático que, tras varios sucesos violentos, se convierte en proxy de Slender Man.",
        habilidades: ["Agilidad", "Sigilo", "Insensibilidad congénita"],
        tipo: "Psíquico",
        ataque: 85,
        defensa: 98,
        peligroso: true,
    },
    {
        nombre: "Jeff the Killer",
        imagen: "https://i.pinimg.com/736x/70/cc/b9/70ccb915960ab882d97b5673c2642084.jpg",
        descripcion: "Un adolescente desfigurado por un incendio que, tras perder la cordura, recorre las noches en busca de nuevas víctimas mientras susurra su frase característica.",
        habilidades: ["Sonrisa perturbadora", "Fuerza sobrehumana", "Insomnio permanente"],
        tipo: "Oscuro",
        ataque: 90,
        defensa: 70,
        peligroso: true,
    },
    {
        nombre: "Jane the Killer",
        imagen: "https://i.pinimg.com/736x/57/6d/db/576ddba5f739e23ce779237c08932562.jpg",
        descripcion: "Rival jurada de Jeff, quedó desfigurada tras enfrentarlo y ahora lo persigue por venganza, moviéndose entre las sombras con precisión quirúrgica.",
        habilidades: ["Sigilo", "Cuchillos arrojadizos", "Determinación implacable"],
        tipo: "Oscuro",
        ataque: 80,
        defensa: 75,
        peligroso: false,
    },
    {
        nombre: "Eyeless Jack",
        imagen: "https://i.pinimg.com/736x/f1/22/f0/f122f010437279a47565e84571422d01.jpg",
        descripcion: "Una entidad sin ojos que se alimenta de riñones humanos durante la noche, dejando tras de sí escenas quirúrgicas imposibles de explicar.",
        habilidades: ["Visión sin ojos", "Regeneración", "Cirugía improvisada"],
        tipo: "Sobrenatural",
        ataque: 75,
        defensa: 80,
        peligroso: true,
    },
    {
        nombre: "Suicidal Liu",
        imagen: "https://i.pinimg.com/736x/a7/21/e5/a721e55e68b081a5854ce3f02a124acc.jpg",
        descripcion: "El hermano mayor de Jeff, atormentado por la culpa y el trauma tras el incendio que lo desfiguró, lucha contra episodios de autolesión y una ira que a veces no puede controlar.",
        habilidades: ["Fuerza física", "Resiliencia al dolor", "Inestabilidad impredecible"],
        tipo: "Oscuro",
        ataque: 85,
        defensa: 50,
        peligroso: false,
    },
    {
        nombre: "Nina the Killer",
        imagen: "https://i.pinimg.com/736x/20/10/0a/20100ab13827010b742fe4e3fec7bef0.jpg",
        descripcion: "Una admiradora obsesionada con Jeff the Killer que imita su modus operandi con garras improvisadas, dejando un rastro de imitación macabra por donde pasa.",
        habilidades: ["Sigilo obsesivo", "Garras de acero", "Vigilancia constante"],
        tipo: "Oscuro",
        ataque: 78,
        defensa: 68,
        peligroso: true,
    },
    {
        nombre: "BEN Drowned",
        imagen: "https://i.pinimg.com/736x/ab/2e/c7/ab2ec716acd5e86f25d03134a07a75b0.jpg",
        descripcion: "El espíritu de un niño ahogado quedó atrapado en un cartucho de videojuego, manipulando consolas y datos para atraer a nuevas víctimas.",
        habilidades: ["Manipulación de datos", "Posesión de consolas", "Ilusiones"],
        tipo: "Digital",
        ataque: 70,
        defensa: 55,
        peligroso: true,
    },
    {
        nombre: "Sonic.exe",
        imagen: "https://i.pinimg.com/736x/6a/81/59/6a815924ae60db11994034771ee03a82.jpg",
        descripcion: "Una versión corrompida de Sonic que habita un cartucho maldito, atormentando a quien lo juega y manipulando el mundo del juego a su antojo.",
        habilidades: ["Manipulación del juego", "Velocidad sobrenatural", "Terror psicológico"],
        tipo: "Digital",
        ataque: 95,
        defensa: 60,
        peligroso: true,
    },
    {
        nombre: "Laughing Jack",
        imagen: "https://i.pinimg.com/736x/81/17/b0/8117b0f35849c3d39b8375ec73ffa88d.jpg",
        descripcion: "Un payaso demoníaco invocado por la imaginación de un niño, que conserva su apariencia juguetona mientras acecha a quienes se cruzan en su camino.",
        habilidades: ["Invocación de juguetes malditos", "Risa hipnótica", "Inmortalidad"],
        tipo: "Demoníaco",
        ataque: 88,
        defensa: 66,
        peligroso: true,
    },
];

// Si gestion.html ya guardó expedientes agregados con el formulario de
// "Crear", los usamos en vez de la lista fija de arriba, así index.html
// y gestion.html quedan sincronizados a través de localStorage.
const cartasGuardadas = localStorage.getItem("cartas");
if (cartasGuardadas) {
    cartas = JSON.parse(cartasGuardadas);
}
